apiVersion: apps/v1
kind: Deployment
metadata:
  name: erail
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: erail
  template:
    metadata:
      labels:
        app: erail
    spec:
      containers:
        - name: deployment-container
          image: kaushalganatra05/kaushal-image:1.6.9 # {"$imagepolicy":"flux-system:update-image-automation-policy"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
