apiVersion: apps/v1
kind: Deployment
metadata:
  name: erail
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: erail
  template:
    metadata:
      labels:
        app: erail
    spec:
      containers:
        - name: deployment-container
          image: kaushal-image:1.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
