---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: update-image-automation
  namespace: flux-system
spec:
  image: kaushalganatra05/kaushal-image
  interval: 1m0s
