apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
  labels:
    app: eRail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eRail
  template:
    metadata:
      labels:
        app: eRail
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: my-container
        image: kaushal-image:1.0.7
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
