---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: update-image-automation-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: update-image-automation
  policy:
    semver:
      range: 1.x.0
