apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-update-controller-binding
subjects:
- kind: ServiceAccount
  name: image-automation-controller
  namespace: flux-system
roleRef:
  kind: ClusterRole
  name: image-update-controller-role
  apiGroup: rbac.authorization.k8s.io
