apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-update-controller-role
rules:
- apiGroups: ["image.toolkit.fluxcd.io"]
  resources: ["imageupdateautomations"]
  verbs: ["get", "list", "watch"]
